kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-operator
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - get
      - watch
      - list
      - update
      - patch
    # echo '- ""' && kubectl api-resources -o name | tail -n +1 | grep '.' | cut -d'.' -f2- | awk '{print "- " $1}' | sort -u
  - apiGroups:
      - ""
      - acid.zalan.do
      - acme.cert-manager.io
      - admissionregistration.k8s.io
      - apiextensions.k8s.io
      - apiregistration.k8s.io
      - apm.k8s.elastic.co
      - apps
      - authentication.istio.io
      - authentication.k8s.io
      - authorization.k8s.io
      - autoscaling
      - batch
      - bindings
      - cert-manager.io
      - certificates.k8s.io
      - componentstatuses
      - config.istio.io
      - configmaps
      - coordination.k8s.io
      - crd.k8s.amazonaws.com
      - elasticsearch.k8s.elastic.co
      - endpoints
      - etcd.database.coreos.com
      - events
      - events.k8s.io
      - extensions
      - jaegertracing.io
      - kibana.k8s.elastic.co
      - limitranges
      - metrics.k8s.io
      - miniocontroller.min.io
      - networking.istio.io
      - networking.k8s.io
      - node.k8s.io
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - podtemplates
      - policy
      - rbac.authorization.k8s.io
      - rbac.istio.io
      - redisoperator.k8s.io
      - replicationcontrollers
      - resourcequotas
      - scheduling.k8s.io
      - secrets
      - serviceaccounts
      - services
      - storage.k8s.io
    # kubectl api-resources | tail -n +2 | cut -d' ' -f1 | awk '{print "- " $1}' | grep -v namespaces
    resources:
      - bindings
      - componentstatuses
      - configmaps
      - endpoints
      - events
      - limitranges
      - nodes
      - persistentvolumeclaims
      - persistentvolumes
      - pods
      - podtemplates
      - replicationcontrollers
      - resourcequotas
      - secrets
      - serviceaccounts
      - services
      - operatorconfigurations
      - postgresqls
      - challenges
      - orders
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
      - customresourcedefinitions
      - apiservices
      - apmservers
      - controllerrevisions
      - daemonsets
      - deployments
      - replicasets
      - statefulsets
      - meshpolicies
      - policies
      - tokenreviews
      - localsubjectaccessreviews
      - selfsubjectaccessreviews
      - selfsubjectrulesreviews
      - subjectaccessreviews
      - horizontalpodautoscalers
      - cronjobs
      - jobs
      - certificaterequests
      - certificates
      - clusterissuers
      - issuers
      - certificatesigningrequests
      - adapters
      - attributemanifests
      - handlers
      - httpapispecbindings
      - httpapispecs
      - instances
      - quotaspecbindings
      - quotaspecs
      - rules
      - templates
      - leases
      - eniconfigs
      - elasticsearches
      - etcdbackups
      - etcdclusters
      - etcdrestores
      - events
      - daemonsets
      - deployments
      - ingresses
      - networkpolicies
      - podsecuritypolicies
      - replicasets
      - jaegers
      - kibanas
      - nodes
      - pods
      - minioinstances
      - destinationrules
      - envoyfilters
      - gateways
      - serviceentries
      - sidecars
      - virtualservices
      - ingresses
      - networkpolicies
      - runtimeclasses
      - poddisruptionbudgets
      - podsecuritypolicies
      - clusterrolebindings
      - clusterroles
      - rolebindings
      - roles
      - authorizationpolicies
      - clusterrbacconfigs
      - rbacconfigs
      - servicerolebindings
      - serviceroles
      - redisclusters
      - priorityclasses
      - csidrivers
      - csinodes
      - storageclasses
      - volumeattachments
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-operator
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k8s-operator
