kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-reader
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - apiextensions.k8s.io
      - metrics.k8s.io
      - networking.k8s.io
      - rbac.authorization.k8s.io
      - storage.k8s.io
    resources:
      - bindings
      - clusterroles
      - clusterrolebindings      
      - componentstatuses
      - configmaps
      - cronjobs
      - customresourcedefinitions
      - daemonsets
      - deployments
      - deployments/scale
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingresses
      - jobs
      - limitranges
      - namespaces
      - namespaces/status
      - networkpolicies
      - nodes
      - poddisruptionbudgets
      - pods
      - pods/log
      - pods/status
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - resourcequotas/status
      - replicasets
      - replicasets/scale
      - replicationcontrollers
      - replicationcontrollers/scale
      - replicationcontrollers/status
      - roles
      - rolebindings
      - serviceaccounts
      - services
      - statefulsets
      - storageclasses
      - volumeattachments
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k8s-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubernetes-dashboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-reader
subjects:
- kind: ServiceAccount
  name: dashboard
  namespace: monitor
