kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-responder
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
    resources:
      - configmaps
      - cronjobs
      - horizontalpodautoscalers
      - secrets
      - daemonsets
      - deployments
      - statefulsets
    verbs:
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-responder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-responder
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: k8s-responder
